export enum ReviewsActionType {
  FETCH_REVIEWS_START = 'FETCH_REVIEWS_START',
  FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS',
  FETCH_REVIEWS_FAILED = 'FETCH_REVIEWS_FAILED',
  ADD_REVIEW_START = 'ADD_REVIEW_START',
  ADD_REVIEW_FAILED = 'ADD_REVIEW_FAILED',
  ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS',
  DELETE_REVIEW_START = 'DELETE_REVIEW_START',
  DELETE_REVIEW_FAILED = 'DELETE_REVIEW_FAILED',
  DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS',
  EDIT_REVIEW_START = 'EDIT_REVIEW_START',
  EDIT_REVIEW_FAILED = 'EDIT_PREVIEW_FAILED',
  EDIT_REVIEW_SUCCESS = 'EDIT_PREVIEW_SUCCESS',
}
